services:
  - type: web
    name: missing-persons-backend
    runtime: go
    buildCommand: |
      go mod download
      go build -o server .
    startCommand: ./server
    envVars:
      - key: GO_ENV
        value: production
      - key: PORT
        value: "8081"  